identifier: l5dc77ef0cxer6b1
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: portfolio
homeFolder: /Users/sirvio/gitRepos/jaausi.github.io/portfolio
distFolder: dist/portfolio
outDir: /Users/sirvio/gitRepos/jaausi.github.io/portfolio/dist/static
handle404: ''
allowErrorCollect: false
