name: Scully Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: cmgriffing/scully-gh-pages-action@v10
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: deploy
