name: Scully Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: jaausi/scully-gh-pages-action@3dea7e58238ed453982709b0390d5b2e0b981b39
        with:
          access-token: ${{ secrets.PORTFOLIO_PUBLISH }}
